---
dataMaid: yes
title: Codebook for merge_test_train_mean_std
subtitle: "Autogenerated data summary from dataMaid"
date: 2018-07-13 14:09:17
output: word_document
---
```{r , echo=FALSE, include=FALSE, warning=FALSE, message=FALSE, error=FALSE}
library(ggplot2)
library(pander)
```
# Data report overview
The dataset examined has the following dimensions:


---------------------------------
Feature                    Result
------------------------ --------
Number of observations      10299

Number of variables            68
---------------------------------












































































































































# Codebook summary table

---------------------------------------------------------------------------------------------------------------------
Label   Variable                                                       Class         # unique  Missing  Description  
                                                                                       values                        
------- -------------------------------------------------------------- ----------- ---------- --------- -------------
        **[subject]**                                                  integer             30  0.00 %                

        **[activity]**                                                 character            6  0.00 %                

        **[Time.Domain.Body.Acceleration.Signal-                       numeric          10292  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Signal-                       numeric          10299  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Signal-                       numeric          10293  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Signal-                       numeric          10295  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Signal-                       numeric          10297  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Signal-                       numeric          10297  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Gravity.Acceleration.Signal-                    numeric          10296  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Gravity.Acceleration.Signal-                    numeric          10298  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Gravity.Acceleration.Signal-                    numeric          10299  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Gravity.Acceleration.Signal-                    numeric          10288  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Gravity.Acceleration.Signal-                    numeric          10293  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Gravity.Acceleration.Signal-                    numeric          10296  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Jerk.Signal-                  numeric          10299  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Jerk.Signal-                  numeric          10299  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Jerk.Signal-                  numeric          10299  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Jerk.Signal-                  numeric          10290  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Jerk.Signal-                  numeric          10296  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Jerk.Signal-                  numeric          10293  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Signal-                           numeric          10298  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Signal-                           numeric          10299  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Signal-                           numeric          10297  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Signal-                           numeric          10292  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Signal-                           numeric          10296  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Signal-                           numeric          10296  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Jerk.Signal-                      numeric          10295  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Jerk.Signal-                      numeric          10299  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Jerk.Signal-                      numeric          10298  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Jerk.Signal-                      numeric          10292  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Jerk.Signal-                      numeric          10295  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Gyration.Jerk.Signal-                      numeric          10291  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Signal.Magnitude-             numeric          10296  0.00 %                
        mean]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Signal.Magnitude-             numeric          10294  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Time.Domain.Gravity.Acceleration.Signal.Magnitude-          numeric          10296  0.00 %                
        mean]**                                                                                                      

        **[Time.Domain.Gravity.Acceleration.Signal.Magnitude-          numeric          10294  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Time.Domain.Body.Acceleration.Jerk.Signal.Magnitude-        numeric          10292  0.00 %                
        mean]**                                                                                                      

        **[Time.Domain.Body.Acceleration.Jerk.Signal.Magnitude-        numeric          10294  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Time.Domain.Body.Gyration.Magnitude-                        numeric          10298  0.00 %                
        mean]**                                                                                                      

        **[Time.Domain.Body.Gyration.Magnitude-                        numeric          10298  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Time.Domain.Body.Gyration.Jerk.Signal.Magnitude-            numeric          10293  0.00 %                
        mean]**                                                                                                      

        **[Time.Domain.Body.Gyration.Jerk.Signal.Magnitude-            numeric          10297  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Frequency.Domain.Body.Acceleration.Signal-                  numeric          10295  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Signal-                  numeric          10292  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Signal-                  numeric          10295  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Signal-                  numeric          10294  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Signal-                  numeric          10297  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Signal-                  numeric          10296  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal-             numeric          10293  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal-             numeric          10296  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal-             numeric          10294  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal-             numeric          10291  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal-             numeric          10294  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal-             numeric          10290  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Signal-                      numeric          10297  0.00 %                
        mean-X                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Signal-                      numeric          10296  0.00 %                
        mean-Y                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Signal-                      numeric          10297  0.00 %                
        mean-Z                                                                                                       
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Signal-                      numeric          10297  0.00 %                
        std                                                                                                          
        dev-X                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Signal-                      numeric          10293  0.00 %                
        std                                                                                                          
        dev-Y                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Signal-                      numeric          10295  0.00 %                
        std                                                                                                          
        dev-Z                                                                                                        
        axis]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Signal.Magnitude-        numeric          10296  0.00 %                
        mean]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Signal.Magnitude-        numeric          10298  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal.Magnitude-   numeric          10290  0.00 %                
        mean]**                                                                                                      

        **[Frequency.Domain.Body.Acceleration.Jerk.Signal.Magnitude-   numeric          10296  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Frequency.Domain.Body.Gyration.Magnitude-                   numeric          10297  0.00 %                
        mean]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Magnitude-                   numeric          10296  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       

        **[Frequency.Domain.Body.Gyration.Jerk.Signal.Magnitude-       numeric          10293  0.00 %                
        mean]**                                                                                                      

        **[Frequency.Domain.Body.Gyration.Jerk.Signal.Magnitude-       numeric          10292  0.00 %                
        std                                                                                                          
        dev]**                                                                                                       
---------------------------------------------------------------------------------------------------------------------




# Variable list
## subject


-----------------------------------
Feature                      Result
------------------------- ---------
Variable type               integer

Number of missing obs.      0 (0 %)

Number of unique values          30

Median                           17

1st and 3rd quartiles         9; 24

Min. and max.                 1; 30
-----------------------------------




---

## activity


-------------------------------------
Feature                        Result
------------------------- -----------
Variable type               character

Number of missing obs.        0 (0 %)

Number of unique values             6

Mode                         "LAYING"
-------------------------------------




---

## Time.Domain.Body.Acceleration.Signal- mean-X axis


--------------------------------------
Feature                         Result
------------------------- ------------
Variable type                  numeric

Number of missing obs.         0 (0 %)

Number of unique values          10292

Median                            0.28

1st and 3rd quartiles       0.26; 0.29

Min. and max.                    -1; 1
--------------------------------------




---

## Time.Domain.Body.Acceleration.Signal- mean-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10299

Median                             -0.02

1st and 3rd quartiles       -0.02; -0.01

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Signal- mean-Z axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10293

Median                            -0.11

1st and 3rd quartiles       -0.12; -0.1

Min. and max.                     -1; 1
---------------------------------------




---

## Time.Domain.Body.Acceleration.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10295

Median                             -0.94

1st and 3rd quartiles       -0.99; -0.25

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.84

1st and 3rd quartiles       -0.98; -0.06

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Signal- std dev-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.85

1st and 3rd quartiles       -0.98; -0.28

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal- mean-X axis


--------------------------------------
Feature                         Result
------------------------- ------------
Variable type                  numeric

Number of missing obs.         0 (0 %)

Number of unique values          10296

Median                            0.92

1st and 3rd quartiles       0.81; 0.95

Min. and max.                    -1; 1
--------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal- mean-Y axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10298

Median                            -0.14

1st and 3rd quartiles       -0.24; 0.12

Min. and max.                     -1; 1
---------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal- mean-Z axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10299

Median                             0.04

1st and 3rd quartiles       -0.12; 0.22

Min. and max.                     -1; 1
---------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10288

Median                             -0.98

1st and 3rd quartiles       -0.99; -0.96

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10293

Median                             -0.98

1st and 3rd quartiles       -0.99; -0.95

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal- std dev-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.97

1st and 3rd quartiles       -0.99; -0.93

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal- mean-X axis


--------------------------------------
Feature                         Result
------------------------- ------------
Variable type                  numeric

Number of missing obs.         0 (0 %)

Number of unique values          10299

Median                            0.08

1st and 3rd quartiles       0.06; 0.09

Min. and max.                    -1; 1
--------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal- mean-Y axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10299

Median                             0.01

1st and 3rd quartiles       -0.02; 0.03

Min. and max.                     -1; 1
---------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal- mean-Z axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10299

Median                                0

1st and 3rd quartiles       -0.03; 0.02

Min. and max.                     -1; 1
---------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10290

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.29

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.93

1st and 3rd quartiles       -0.99; -0.22

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal- std dev-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10293

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.55

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Signal- mean-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10298

Median                             -0.03

1st and 3rd quartiles       -0.05; -0.01

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Signal- mean-Y axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10299

Median                            -0.07

1st and 3rd quartiles       -0.1; -0.05

Min. and max.                     -1; 1
---------------------------------------




---

## Time.Domain.Body.Gyration.Signal- mean-Z axis


--------------------------------------
Feature                         Result
------------------------- ------------
Variable type                  numeric

Number of missing obs.         0 (0 %)

Number of unique values          10297

Median                            0.09

1st and 3rd quartiles       0.06; 0.11

Min. and max.                    -1; 1
--------------------------------------




---

## Time.Domain.Body.Gyration.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10292

Median                              -0.9

1st and 3rd quartiles       -0.99; -0.48

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.91

1st and 3rd quartiles       -0.98; -0.45

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Signal- std dev-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.88

1st and 3rd quartiles       -0.99; -0.34

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal- mean-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10295

Median                              -0.1

1st and 3rd quartiles       -0.12; -0.08

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal- mean-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10299

Median                             -0.04

1st and 3rd quartiles       -0.06; -0.03

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal- mean-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10298

Median                             -0.05

1st and 3rd quartiles       -0.08; -0.03

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10292

Median                             -0.93

1st and 3rd quartiles       -0.99; -0.49

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10295

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.63

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal- std dev-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10291

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.51

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Signal.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.87

1st and 3rd quartiles       -0.98; -0.12

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Signal.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10294

Median                             -0.84

1st and 3rd quartiles       -0.98; -0.24

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.87

1st and 3rd quartiles       -0.98; -0.12

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Gravity.Acceleration.Signal.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10294

Median                             -0.84

1st and 3rd quartiles       -0.98; -0.24

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal.Magnitude- mean


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10292

Median                            -0.95

1st and 3rd quartiles       -0.99; -0.3

Min. and max.                     -1; 1
---------------------------------------




---

## Time.Domain.Body.Acceleration.Jerk.Signal.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10294

Median                             -0.93

1st and 3rd quartiles       -0.99; -0.27

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10298

Median                             -0.82

1st and 3rd quartiles       -0.98; -0.25

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10298

Median                             -0.83

1st and 3rd quartiles       -0.98; -0.39

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10293

Median                             -0.96

1st and 3rd quartiles       -0.99; -0.55

Min. and max.                      -1; 1
----------------------------------------




---

## Time.Domain.Body.Gyration.Jerk.Signal.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.94

1st and 3rd quartiles       -0.99; -0.61

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal- mean-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10295

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.26

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal- mean-Y axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10292

Median                            -0.86

1st and 3rd quartiles       -0.98; -0.1

Min. and max.                     -1; 1
---------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal- mean-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10295

Median                              -0.9

1st and 3rd quartiles       -0.98; -0.37

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10294

Median                             -0.94

1st and 3rd quartiles       -0.99; -0.25

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.83

1st and 3rd quartiles       -0.98; -0.09

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal- std dev-Z axis


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values           10296

Median                            -0.84

1st and 3rd quartiles       -0.98; -0.3

Min. and max.                     -1; 1
---------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal- mean-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10293

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.33

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal- mean-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.93

1st and 3rd quartiles       -0.98; -0.26

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal- mean-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10294

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.51

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10291

Median                             -0.96

1st and 3rd quartiles       -0.99; -0.32

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10294

Median                             -0.93

1st and 3rd quartiles       -0.99; -0.24

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal- std dev-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10290

Median                             -0.96

1st and 3rd quartiles       -0.99; -0.59

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Signal- mean-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.89

1st and 3rd quartiles       -0.99; -0.38

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Signal- mean-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.92

1st and 3rd quartiles       -0.98; -0.47

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Signal- mean-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.89

1st and 3rd quartiles       -0.99; -0.32

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Signal- std dev-X axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.91

1st and 3rd quartiles       -0.99; -0.52

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Signal- std dev-Y axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10293

Median                             -0.91

1st and 3rd quartiles       -0.98; -0.44

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Signal- std dev-Z axis


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10295

Median                             -0.89

1st and 3rd quartiles       -0.99; -0.42

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.88

1st and 3rd quartiles       -0.98; -0.22

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Signal.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10298

Median                             -0.85

1st and 3rd quartiles       -0.98; -0.38

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10290

Median                             -0.93

1st and 3rd quartiles       -0.99; -0.26

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Acceleration.Jerk.Signal.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.93

1st and 3rd quartiles       -0.99; -0.31

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10297

Median                             -0.88

1st and 3rd quartiles       -0.98; -0.45

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10296

Median                             -0.83

1st and 3rd quartiles       -0.98; -0.47

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Jerk.Signal.Magnitude- mean


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10293

Median                             -0.95

1st and 3rd quartiles       -0.99; -0.61

Min. and max.                      -1; 1
----------------------------------------




---

## Frequency.Domain.Body.Gyration.Jerk.Signal.Magnitude- std dev


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values            10292

Median                             -0.94

1st and 3rd quartiles       -0.99; -0.64

Min. and max.                      -1; 1
----------------------------------------




---



Report generation information:

 *  Created by Megan Brennan (username: `megan`).

 *  Report creation time: Fri Jul 13 2018 14:09:18

 *  Report Was run from directory: `C:/Users/megan/Documents/dataRStudio`

 *  dataMaid v1.1.2 [Pkg: 2018-05-03 from CRAN (R 3.5.1)]

 *  R version 3.5.0 (2018-04-23).

 *  Platform: x86_64-w64-mingw32/x64 (64-bit)(Windows >= 8 x64 (build 9200)).

 *  Function call: `makeDataReport(data = merge_test_train_mean_std, mode = "summarize", 
    file = "codebook_merge_test_train_mean_std.Rmd", checks = list(
        list("showAllFactorLevels")), listChecks = FALSE, maxProbVals = FALSE, 
    codebook = TRUE, reportTitle = "Codebook for merge_test_train_mean_std")`

